#!/bin/bash
#****************************************************************************
#* edapack
#*
#* Command wrapper for EDAPack
#****************************************************************************

if test -f $0; then
  script_dir=$(dirname $0)
  script_dir=$(cd $script_dir ; pwd)
else
  # Find ourselves in the PATH
  for elem in $(echo PATH | sed -e 's%:% %g'); do
    script=${elem}/$0
    if test -f $script; then
      script_dir=$elem
      break
    fi
  done
fi

edapack_dir=$(dirname $script_dir)

export PYTHONPATH=${edapack_dir}/lib

exec ${edapack_dir}/python3/bin/python3 -m edapack ${@:1}


