#!/bin/bash
#****************************************************************************
#* edapack
#*
#* Command wrapper for EDAPack
#****************************************************************************

bin_dir="$(cd "$(dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd)"
edapack_dir=$(dirname $bin_dir)

export PYTHONPATH=${edapack_dir}/lib/edapack.zip

exec ${edapack_dir}/python3/bin/python3 -m edapack ${@:1}


